spring.application.name=node

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/flux-node
spring.datasource.username=postgres
spring.datasource.password=youknowme
# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Optional: Better logging
spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx
# Log levels
logging.level.root=INFO
logging.level.com.flux.node=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE



# JWT

jwt.secret = 7cRWpwZ5vLdz5Y0FTdEPE3Fnz3NijdyOFYKgqL4ZgPw
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000


# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379